#name: Java CI with Gradle
#
#on:
#  push:
#    branches: [ main ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'zulu'
#      - name: Set Yaml
#        uses: microsoft/variable-substitution@v1
#        with:
#          files: ./src/main/resources/application-deploy.yml
#        env:
#          spring.datasource.url: ${{ secrets.DB_URL }}
#          spring.datasource.password: ${{ secrets.RDS_PASSWORD }}
#          spring.config.domain: ${{ secrets.AWS_S3_ENDPOINT }}
#          spring.security.oauth2.client.registration.google.clientId: ${{ secrets.G_CLIENT_ID }}
#          spring.security.oauth2.client.registration.google.clientSecret: ${{ secrets.G_CLIENT_SECRET }}
#          jwt.key.secret: ${{ secrets.JWT_SECRET_KEY }}
#          cloud.credentials.accessKey: ${{ secrets.S3_ACCESS_KEY }}
#          cloud.credentials.secretKey: ${{ secrets.S3_SECRET_KEY }}
#          api.key: ${{ secrets.API_SERVICE_KEY }}
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
#      - name: Docker build
#        run: |
#          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
#          docker build -t marbleus-cicd .
#          docker tag marbleus-cicd ${{ secrets.DOCKER_HUB_USERNAME }}/spring-cicd:${GITHUB_SHA::7}
#          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-cicd:${GITHUB_SHA::7}
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#      - name: Start Session Manager session
#        run: aws ssm start-session --target i-02b2c9f494fbf4e67
#      - name: Deploy to Server
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: ap-northeast-2
#        run: |
#          aws ssm send-command \
#            --instance-ids i-02b2c9f494fbf4e67 \
#            --document-name "AWS-RunShellScript" \
#            --parameters "commands=[
#              'if sudo docker ps -a --format \\'{{.Names}}\\' | grep -q \'^server$\\'; then',
#              '  sudo docker stop server',
#              '  sudo docker rm server',
#              'fi',
#              'sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/spring-cicd:${GITHUB_SHA::7}',
#              'sudo docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/spring-cicd:${GITHUB_SHA::7} spring-cicd',
#              'sudo docker run -d --name server -p 8080:8080 spring-cicd'
#            ]" \
#            --output text
